"""Unit tests for LangGraph chatbot workflow nodes and state graph compilation."""

from typing import TYPE_CHECKING

import pytest

from app.core.exceptions import ValidationError
from app.domain.messages import CanonicalMessage, MessageRole
from app.graph.chatbot import build_chat_graph
from app.graph.nodes import GenerateNode, format_node, validate_node
from app.llm.mock import MockLLMService

if TYPE_CHECKING:
    from app.graph.state import ChatGraphState


def test_validate_node_valid_messages() -> None:
    """Verify validation node passes when state contains non-empty user messages."""
    msg = CanonicalMessage.from_text("Hello LangGraph")
    state: ChatGraphState = {"messages": [msg], "response": None, "error": None}

    result = validate_node(state)
    assert result == {}


def test_validate_node_empty_messages() -> None:
    """Verify validation node raises ValidationError when messages list is empty."""
    state: ChatGraphState = {"messages": [], "response": None, "error": None}

    with pytest.raises(ValidationError) as exc_info:
        validate_node(state)

    assert "empty message sequence" in str(exc_info.value.message)


@pytest.mark.asyncio
async def test_generate_node_executes_service() -> None:
    """Verify GenerateNode delegates generation to injected ILLMService."""
    mock_llm = MockLLMService(default_response="Generated by node")
    node = GenerateNode(mock_llm)

    msg = CanonicalMessage.from_text("Test prompt")
    state: ChatGraphState = {"messages": [msg], "response": None, "error": None}

    result = await node(state)

    assert "response" in result
    assert result["response"].text == "Generated by node"
    assert result["response"].role == MessageRole.ASSISTANT


def test_format_node_success() -> None:
    """Verify format node returns response state."""
    resp_msg = CanonicalMessage.from_text("Formatted reply", role=MessageRole.ASSISTANT)
    state: ChatGraphState = {"messages": [], "response": resp_msg, "error": None}

    result = format_node(state)
    assert result["response"] == resp_msg


def test_format_node_missing_response() -> None:
    """Verify format node raises ValidationError when response is None."""
    state: ChatGraphState = {"messages": [], "response": None, "error": None}

    with pytest.raises(ValidationError):
        format_node(state)


@pytest.mark.asyncio
async def test_chat_graph_end_to_end_execution() -> None:
    """Verify full compiled LangGraph workflow end-to-end execution."""
    mock_llm = MockLLMService(default_response="End-to-end LangGraph reply")
    graph = build_chat_graph(mock_llm)

    input_message = CanonicalMessage.from_text("Hello workflow")
    initial_state: ChatGraphState = {
        "messages": [input_message],
        "response": None,
        "error": None,
    }

    final_state = await graph.ainvoke(initial_state)

    assert final_state["response"] is not None
    assert final_state["response"].text == "End-to-end LangGraph reply"
    assert final_state["response"].role == MessageRole.ASSISTANT
    assert len(mock_llm.recorded_calls) == 1
